### ISSUE TITLE
Empty lines in code blocks not displayed correctly

### ISSUE THREAD

**Issue by dsyer** [visit1985/mdp#100]
The fix for #96 made sure that empty lines in a code block are "coloured" (i.e. counted as part of the code), but the empty lines have a different line width than the non-empty lines, so it's still ugly.

![lines-width](https://cloud.githubusercontent.com/assets/124075/13226307/bacf258e-d988-11e5-83e2-0ec37239f1db.png)

**Comment by visit1985** [comment]
Do your empty lines have the same indentation?

**Comment by dsyer** [comment]
Yes (none, because they are in a fenced block, maybe that's the bug?).

**Comment by visit1985** [comment]
I can't reproduce this.

![image](https://cloud.githubusercontent.com/assets/2237222/13511740/c3eadcf6-e196-11e5-8d34-74452c1c1650.png)

I test via rxvt-unicode (ncurses 6.0) on Arch Linux.
What's your setup?

**Comment by dsyer** [comment]
I have a stock Ubuntu 14.04.

**Comment by dsyer** [comment]
I have a workaround, which is to put a non-breaking space at the start of an empty line. It would be nice to not have to do that I guess.

**Comment by visit1985** [comment]
I was able to reproduce it:
![bug](https://cloud.githubusercontent.com/assets/2237222/13898857/a1d8e11c-eddf-11e5-8793-b3f1d954313f.gif)

The issue seams to be caused by commit 51259296, which was a fix for cygwin.
Have to double-check on Windows...

**Comment by visit1985** [comment]
Fix looks good on cygwin.
@dsyer, can you cross-check in Ubuntu 14.04 please?

**Comment by dsyer** [comment]
It's mostly OK. I think maybe there's a new problem though because a "long leader" in a code block sometimes still appears (on different lines than before, this time non-empty lines), they also sometimes remain on the screen after the slide has changed (and there is no code block):

![image](https://cloud.githubusercontent.com/assets/124075/13959534/7128b528-f04c-11e5-8b7c-dc55a6e904a6.png)

**Comment by visit1985** [comment]
I can't reproduce the list issue on Ubuntu 16.04. Can you provide your complete sample (maybe via [pastebin.com](http://pastebin.com/))?
