### ISSUE TITLE
libsixel support?

### ISSUE THREAD

**Issue by vrthra** [visit1985/mdp#105]
Any chance of supporting images using `[libsixel](https://github.com/saitoha/libsixel)`?

**Comment by visit1985** [comment]
https://github.com/visit1985/mdp/issues/54

**Comment by vrthra** [comment]
@visit1985 I understand. I noticed in #54, your comment that `Images don't look good if rendered down to 48x48 px max`. Just wanted to mention that `sixel` can produce true images. E.g. see ![this](http://i.imgur.com/8I3Gv8x.png) that displays a pdf in the terminal. Also, sixel
is a standard and hence the support may come to most terminals eventually.
