### ISSUE TITLE
files with no slides

### ISSUE THREAD

**Issue by idprism** [visit1985/mdp#106]
instead of errors like: 
Error: Terminal height (58 lines) too small. Need at least 251 lines for slide #1.
You may need to add additional horizontal rules (---) to split your file in shorter slides.

can we just have a mode where we dont have slides and instead just page through like a normal paginator? is there a different project for that?

**Comment by visit1985** [comment]
Unfortunately that's not as easy as it sounds. The internal data structure of mdp is not flexible enough to solve #15. And a paginator is even more complex. We would need to redesign the whole app for that, which I don't have the spare time for.

Additionally we'd need to disable the pandoc URL feature, which stacks bottom-up on each page.

I'm not aware of a different project, which fulfills that need.

**Comment by idprism** [comment]
well, thank you for the consideration. I will look elsewhere to read the random unpaged markdown README.md I always get in software packages, but I will definitely keep mdp around for anything that already has enough rules to have pages.

**Comment by oising** [comment]
What about just inserting page breaks (---) automatically? I understand full and intelligent pagination is going to be harder, but I'd rather a dumb algorithm than none at all :)
