### ISSUE TITLE
Empty slides on iTerm2 v3.0.5

### ISSUE THREAD

**Issue by piotron** [visit1985/mdp#107]
_Software information:_
current master branch compiled on alpine linux running in docker 1.12

_Problem:_ 
two or three slides after first are blank on iTerm2, probably fading problem.

_Temporary solution:_ 
goto next slide then hit 'r', you are going back but then you can see all slides.

_Possible solution:_ 
add option to turn off fading between slides.

**Comment by visit1985** [comment]
There is an option -f / --nofade already.

**Comment by visit1985** [comment]
@piotron does it help?

**Comment by piotron** [comment]
I've tried it few times, but this makes first slide invisible, and some footer parsing problems

**Comment by visit1985** [comment]
Testet on OS-X with iTerm2 3.0.13
Can't reproduce.
