### ISSUE TITLE
Reload 'r' quits mdp on first slide

### ISSUE THREAD

**Issue by ryyppy** [visit1985/mdp#108]
Currently I open my slides side by side via tmux, edit the file and hit the `r` button on mdp in another pane... 

* If I am on slide 2, mdp will go back one slide and reload the input file
* If I am on slide 1, mdp will quit

Is this expected behavior?

**Comment by visit1985** [comment]
Issue was introduced in 4ebae8ba8f3700f740d2705f7a3c2dc92f4995dc.
Thanks for finding it!

**Comment by ryyppy** [comment]
Great! Love this tool btw 👍
