### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [visit1985/mdp#112]
Dear Michael,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by grigory-rechistov** [comment]
`mdp` is perfectly buildable within Cygwin environment on Windows. Provided one has all dependencies installed though its package management system.

**Comment by visit1985** [comment]
Last time I tried to build a static win32 binary of mdp, it was detected malicious by avira/kasperski. Maybe someone with more win32 build experience can step in here. Or we can try to get it into the [cygwin repo](https://cygwin.com/setup.html).

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by visit1985** [comment]
https://www.cygwin.com/ml/cygwin-apps/2016-12/msg00038.html

**Comment by sergeevabc** [comment]
@visit1985, is there a way to get a dependent-free binary, i.e. that runs w/o ```cygwin1.dll```?

**Comment by visit1985** [comment]
At least not from my side. I don't have the time and knowledge to do that.

Why would you even want that? You need a decent terminal with UTF-8 support and 256 colors anyway. Mintty, which is the default in Cygwin, gives you all that.

**Comment by visit1985** [comment]
https://cygwin.com/ml/cygwin/2017-01/msg00306.html

**Comment by sergeevabc** [comment]
Both @visit1985’s [link][1] and frontpage’s [link][2] lead nowhere near the required binary. Correct [link].

[1]: https://cygwin.com/ml/cygwin/2017-01/msg00306.html
[2]: https://cygwin.com/cgi-bin2/package-grep.cgi?grep=mdp.exe
[3]: http://www.cygwin.com/ml/cygwin-apps/2016-12/msg00038.html

**Comment by visit1985** [comment]
@sergeevabc You can simply download the cygwin installer and choose mdp from the package list.

**Comment by sergeevabc** [comment]
Think of early firearms which required user to carry a heavy ramrod to push the projectile up against the gunpowder before shooting. It still serves the purpose today, but abandoned due to awkwardness. Back to software: some of us derive from a measured pace milieu with a willing to pollute system with  dependencies to get things done, others prefer to stay green and travel light.
