### ISSUE TITLE
Support for GitHub flavored Markdown codeblocks

### ISSUE THREAD

**Issue by Naereen** [visit1985/mdp#116]
Hi,
First, great job and :clap: for this nice little tool, it's nice!

### Bug
Do you think you could (easily) add support to [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) syntax for code blocks?
Right now, a block starting with three `~~~` works, but if starts with three backticks or with three backticks and a language hint:
```markdown
```python
...
```
it doesn't work anymore.

### Example
Here is an example (`mdp` output on top, content of the slides file below):
- With `~~~`:
![bug mdp 2](https://cloud.githubusercontent.com/assets/11994719/23117993/b0e8a354-f752-11e6-93bc-07da7ea920e4.png)

- With backticks:
![bug mdp](https://cloud.githubusercontent.com/assets/11994719/23118006/c503c35a-f752-11e6-8198-c551c58bfe52.png)

---
Thanks in advance!

**Comment by visit1985** [comment]
Shouldn't be difficult. I can do it when I find some spare time.
`src/parser.c#L430`

**Comment by Naereen** [comment]
Oh, you wrote the parser yourself? There is so many libraries doing that, I thought you just used one.
Take your time, that's not urgent :smile:

**Comment by titipata** [comment]
+1 on this issue!
