### ISSUE TITLE
Error: Terminal height (xx lines) too small

### ISSUE THREAD

**Issue by greencopper** [visit1985/mdp#117]
No matter what markdown file I open I get something like:

```
Error: Terminal height (42 lines) too small. Need at least 249 lines for slide #1.
You may need to add additional horizontal rules (---) to split your file in shorter slides.
```

**Comment by lgalke** [comment]
I also tried to apply `mdp` on markdown files out of the box. However, you need to insert `---` to seperate frames in the output. A `# h1` header is not automagically considered a frame.

**Comment by visit1985** [comment]
#15
