### ISSUE TITLE
Vertically centred slides?

### ISSUE THREAD

**Issue by spinningarrow** [visit1985/mdp#125]
Is it possible to have slides vertically centred on the terminal?

**Comment by visit1985** [comment]
Currently this is not possible. The calculation for how many rows are available/needed is quite complex. Especially since we already support pandoc URLs.

You can work around this by inserting empty lines in your slides.

**Comment by spinningarrow** [comment]
I see. Thanks for the response! Unfortunately, the problem with inserting empty lines is the same - it is not aware of how many rows are available so may not always be centred (while presenting, I often increase the font size of the terminal till it looks big enough and it's hard to gauge how many lines will be available).

**Comment by visit1985** [comment]
Awesome @ethanherbertson, thanks a lot! 🙌
