### ISSUE TITLE
Feature Request: Load Markdown from URL

### ISSUE THREAD

**Issue by spkane** [visit1985/mdp#129]
It would be really useful if you could use this with a URL, like a Github gist:

`mdp https://gist.githubusercontent.com/spkane/43c8571c17e03474d4c472aef621f622/raw/ef18c115189aa0c252a6e7a1ba05c675765e3d63/mdp.md`

**Comment by visit1985** [comment]
Hi @spkane.

mdp supports to read the slides from stdin. It is as easy as

```
curl https://some.url/mdp.md | mdp
```

to grab your slides from an URL.

**Comment by spkane** [comment]
That completely makes sense. I should have considered that. Thanks!
