### ISSUE TITLE
Code blocks not rendering correctly

### ISSUE THREAD

**Issue by pillepalle1** [visit1985/mdp#148]
When embedding code blocks into the presentation, they appear just like a huge, white box across the terminal. The attached screenshot shows the output on st and alacritty

`mdp --version`

mdp 1.0.15
Copyright (C) 2018 Michael Goehler
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Michael Goehler and others, see <https://github.com/visit1985/mdp/blob/master/AUTHORS>.

![image](https://user-images.githubusercontent.com/30006468/117852158-a4e38480-b2b9-11eb-98af-41293705e38c.png)

**Comment by visit1985** [comment]
Seems like this is an issue with sts and alacrittys integration of the ncurses lib then. It works fine in many other terminal emulators, like xterm, Gnome terminal, terminator, mintty, iterm2…
