### ISSUE TITLE
Option for kiosk mode

### ISSUE THREAD

**Issue by Schmetzler** [visit1985/mdp#167]
Will there be an option for something like kiosk mode, so that you can create a presentation that runs on its own and repeats itself? Or maybe you can suggest a terminal program that can do that? (I have not found one)

**Comment by visit1985** [comment]
[asciinema](https://docs.asciinema.org/manual/cli/usage/#asciinema-play-filename) can record and replay sessions inside a terminal. Try to put that in a loop and you should be good to go.
