### ISSUE TITLE
Nothing displayed after build/install on Windows 7

### ISSUE THREAD

**Issue by MattSeen** [visit1985/mdp#53]
Version Built: 0.91.1

Machine Spec:

- Windows 7 64bit
- intel i7
- intel integrated graphics

What I see when I run it is the name of the presentation, the author name in the bottom left and the slide count. I can move between each page but the contents are not rendered. The only thing that seemed to be displayed was the rectangle around some text on slide 6.

I followed the build steps apart of the README. Tried it with Cygwin32 and 64 bit to see if there was any kind of difference, still no display. Built the debug version and ran with debug flag haven't been able to come up with any kind of explanation for this issue.

**Comment by visit1985** [comment]
Going to close this now (after 3 months) as not reproducible.
If anyone observes a similar issue and is able to point out the steps to reproduce it, i'd of cause try to fix it.
