### ISSUE TITLE
Reload with 'R' key?

### ISSUE THREAD

**Issue by lukebond** [visit1985/mdp#69]
Love this project! Great job.

Would be great to be able to reload a file with a keypress. I like to iterate on slides, editing them side-by-side with vim. It's a pain to quit, restart, and then jump to slide number (especially if you were on slide > 9).

A quick look at the code suggests it would require a full tear-down of the viewer etc. I'd just create a bunch of memory leaks if I tried to do a quick PR sorry.

**Comment by visit1985** [comment]
Nice idea. I already have something in my mind, how to realized that. Give me some days.

**Comment by lukebond** [comment]
@visit1985 I never formally thanked you for this. I use mdp for all my presentations these days (much to my audiences' annoyance I imagine) and use `r` all the time.

**Comment by visit1985** [comment]
Thanks. Nice to know someone is actually using it.
