### ISSUE TITLE
Coverity Static Analysis Issues

### ISSUE THREAD

**Issue by jodiecunningham** [visit1985/mdp#70]
Hi Michael Göhler,

I added mdp to Coverity and it found a few defects. 
https://scan.coverity.com/projects/3887/

viewer.c:419 -- need delwin(storage) after endwin() to free allocated memory.

viewer.c:109 -- dereference after null check here. Passing null pointer line->text to prev_blank, which dereferences it.

parser.c:95 -- Explicit null dereferenced. Passing null pointer line to next_line, which dereferences it.

markdown.c:81-85 -- dead code branch issue. Code is definitely not null in this branch, but then we null check it. Probably my fault from earlier issues.

**Comment by visit1985** [comment]
@jodiecunningham can you please confirm, if these changes fix the reported defects?

**Comment by jodiecunningham** [comment]
@visit1985  I uploaded the latest build for analysis and Coverity now shows that they've all been fixed.

**Comment by visit1985** [comment]
Thank you for your help!
