### ISSUE TITLE
Unicode block characters give invalid line lengths

### ISSUE THREAD

**Issue by qfjp** [visit1985/mdp#71]
I think the line length calculation is faulty when dealing with special unicode characters. Try the following in a single markdown file:
```    
    ┍━━━━━━━━━━┯━━━━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┑
    │  Cell 1  │   Cell 2    │  Cell 3  │  Cell 4  │
    ┕━━━━━━━━━━┷━━━━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━━━┙
```
mdp reports that it needs 144 columns, though wc gives each line as 49 chars. In addition, trying to center these lines gives incorrect indentation.

**Comment by visit1985** [comment]
@qfjp: The thing is, that mdp currently have kind of a pseudo UTF-8 support is.
It simply handles multi-byte characters as multiple characters.

So I took this opportunity to experimentally add wide character support in branch [wchar_support](https://github.com/visit1985/mdp/tree/wchar_support).
Can you try this version and check if it solves the issue on your maschine?

For me it works, but it needs more extensive testing, as there may be side-effects in different OSes/locales/code-pages.

**Comment by qfjp** [comment]
Looks like this solved it. If it helps, I'm running this in Arch (LANG=en_US.UTF-8)

**Comment by visit1985** [comment]
Merged to master now.
