### ISSUE TITLE
Go to any slide number rather than just 1 to 9

### ISSUE THREAD

**Issue by ahirapatel** [visit1985/mdp#73]
It would be nice if a user could go to more slides than just 1-9. One idea could be to do something like having the user input numbers, then hitting another key to signify jumping to that slide. For example '2' then '3' then 'g' to go to slide 23.

**Comment by visit1985** [comment]
I thought about that too. But my prefered solution would be to type a number and let the page flip happen after a timeout, giving you time to enter the complete number.
