### ISSUE TITLE
Request: Partial Slides

### ISSUE THREAD

**Issue by qfjp** [visit1985/mdp#75]
Is it possible to add markup to "pause" a slide, instead of having to partially duplicate them?

**Comment by visit1985** [comment]
I'm currently working on that (#45). What do you think, which markup should be used for it?

**Comment by qfjp** [comment]
tpp uses '---' (3 dashes), but that probably conflicts with standard markup. Maybe something like ';;'?

**Comment by visit1985** [comment]
I was thinking about a single `^` or `<` in the next line. But it would be better if we find a notation, which is not displayed in converted html.

**Comment by qfjp** [comment]
I don't think markdown has any such notation that will be 'hidden' after
conversion to html, other than using a literal html comment. You could use
a dummy html tag, like '<slide>'. This will convert to <p><slide></p>,
which most browsers should trim anyway. It's not the best solution, but I
don't know of any other way to hide content.

~DJP

**Comment by visit1985** [comment]
Nice idea. Will try that.
