### ISSUE TITLE
Some unicode not supported

### ISSUE THREAD

**Issue by frioux** [visit1985/mdp#80]
💀, for example.

**Comment by visit1985** [comment]
Is this symbol supported by your terminal font? What happens if you paste this symbol in your command-line?

**Comment by frioux** [comment]
Yes, I wrote the markdown for the presentation with vim in the terminal.  Here's some usage of it in the actual command-line:

      $ perl -E"say '<0001f480>'"
      💀

the showing of the code is a zsh feature.

**Comment by visit1985** [comment]
If I run `perl -E 'say "\x{1F480}"'` in my bash, I get a `💀`. What font are you using in your terminal?

**Comment by visit1985** [comment]
Not even chrome can show this char in its address bar: http://graphemica.com/%F0%9F%92%80

**Comment by frioux** [comment]
I use terminus in my terminal.  I'm running latest ubuntu and both firefox and chromium can show the skull in the url bar (not that I see that as being related... ;)

**Comment by visit1985** [comment]
Which OS are you testing from?

**Comment by frioux** [comment]
Ubuntu 14.10

-- 
sent from a rotary phone, pardon my brevity

**Comment by rjbs** [comment]
![___skull__u_1f480____graphemica_and_contacts_and_untitled_3_and_untitled_2_and_untitled](https://cloud.githubusercontent.com/assets/30682/6508092/7b03d5ec-c324-11e4-8ee7-6426ecf40415.png)

**Comment by frioux** [comment]
So to be absolutely clear:

If I put a 💀 in a text file I can read it in vim.  If I put it in a basic command like app, it does display. If I put it in the address bar of either chromium or firefox, it does indeed display.  If I put it in a presentation file, it just does not show at all with mdp.

**Comment by visit1985** [comment]
https://stackoverflow.com/questions/23526353/how-to-get-ncurses-to-output-astral-plane-unicode-characters

**Comment by visit1985** [comment]
So I'll close this, as it is a upstream bug.
