### ISSUE TITLE
Links sorta don't work w/ ^/<br>

### ISSUE THREAD

**Issue by frioux** [visit1985/mdp#81]
So if you do this:

     * chroot
    ^
     * jails  [See history here](http://phk.freebsd.dk/sagas/jails.html)
    ^
     * cgroups
    ^
     * LXC
    ^
     * Docker / LMCTFY [wow lots of containers](http://www.theregister.co.uk/2014/05/23/google_containerization_two_billion/)

The link locations do not render until the final bullet is shown.  I *think* this is a bug.

**Comment by visit1985** [comment]
It is on purpose. ;-)

If we would move the cursor to the bottom and back, we would need to calculate a lot of dependencies (line wrapping, indentation and so on.) which would IMHO bloat the code too much.

If you want to show them inline, don't use pandoc markup.
