### ISSUE TITLE
Cannot reload using 'r'

### ISSUE THREAD

**Issue by jnjzhang** [visit1985/mdp#82]
Reloading does not work on Gnome terminal on Arch Linux. Other keyboard shortcuts wor. flawlessly. It was working on Ubuntu.

**Comment by visit1985** [comment]
Du you get any error message? How do you call mdp?

**Comment by jnjzhang** [comment]
I called with "mdp myfile.md"  No error messages at all.  Other keys worked fine.

**Comment by visit1985** [comment]
Strange. Can't reproduce it. I'm using Arch + Gnome myself, and for me it works.
Does it work for you in rxvt-unicode or xterm under Gnome?

**Comment by visit1985** [comment]
I know you said you used `mdp myfile.md`, but note that `r` is disabled if you pipe content to mdp (`cat myfile.md | mdp`).
