### ISSUE TITLE
?? You may need to add additional horizontal rules (---) to split your file in shorter slides. 

### ISSUE THREAD

**Issue by 43350860** [visit1985/mdp#83]
Error: Terminal height (39 lines) too small. Need at least 187 lines.
You may need to add additional horizontal rules (---) to split your file in shorter slides.

**Comment by visit1985** [comment]
That is the basic concept of mdp. You need to split your markdown file into multiple slides, which are represented by horizontal rules (lines with only `---` in it.

    
    This is a test.
    
    ---
    
    This is a second slide.
