### ISSUE TITLE
Disable fade on 'stop' lines in slides

### ISSUE THREAD

**Issue by nemws1** [visit1985/mdp#94]
Just a suggestion... I added "fade = false;" to line 397 of viewer.c to disable fade when I have a stop on a slide.  I found it odd/unpleasant for the slide to do the fade in/out when most of the content was the same I was just adding a new bullet point.

Not sure if others agree or not.  Maybe a new option?  --nostopfade ?

**Comment by visit1985** [comment]
Jup, I like that idea too. :smile: But I think this is to minor for making it optional.
