### ISSUE TITLE
Ascii art is ugly

### ISSUE THREAD

**Issue by dsyer** [visit1985/mdp#96]
I'm not sure what triggers this. At first I thought it was long lines (which are common in ascii art), but then I tried a quite thin "image" like this:

```
+--------------+
|              |
|              |
|              |
|   Box 1      |
|              |
|              |
|              |
|              |
+----------+---+
               |
               |    +------------+
               |    |            |
               |    |            |
               |    |            |
               +--->+  *Box 2*   |
                    |            |
                    |            |
                    |            |
                    +------------+
```

shows up in mdp with an ugly non-rectangular border:

![image](https://cloud.githubusercontent.com/assets/124075/12418572/06a141f0-bea8-11e5-9261-839b4d24a998.png)

Is there a way to format the input better? Or is it really a bug?

**Comment by visit1985** [comment]
I think backspaces at the beginning of each line should work. Otherwise the preceeding spaces are recognized as code block.

**Comment by dsyer** [comment]
Sorry, I'm not following you. Backspaces are not part of a regular Markdown unless I missed something, so what do you mean exactly? Maybe you can paste me a version of that picture that renders cleanly or something?

Do you think we could keep the issue open until we have finished the conversation?

**Comment by visit1985** [comment]
Of cause they are: https://daringfireball.net/projects/markdown/syntax#backslash

If you want to prevent something from beeing interpreted as markdown, you escape it with backslash. In your case "4 spaces at the beginning of a line" are interpreted as beginning of a code block, and you can prevent that by adding a backslash at the beginning of each line of your ascii art.

https://raw.githubusercontent.com/visit1985/mdp/master/sample.md

**Comment by dsyer** [comment]
Ah, so you said "backspace" when you meant "backslash". That makes more sense. But I'm not convinced really yet, because the whole block of asciiart is inside fences that you say in the sample.md should be interpreted as code block boundaries. Am I missing something still?

**Comment by dsyer** [comment]
This is what it looks like with backslashes:

![image](https://cloud.githubusercontent.com/assets/124075/12433247/deb12926-bef7-11e5-9595-3f0daa701e27.png)

So, I think you'll agree it's not right?

**Comment by visit1985** [comment]
What do you meen with "the whole block of asciiart is inside fences"?

**Comment by dsyer** [comment]
Here:

```
Next Slide
==========

\~~~
+----------------------------+
|                            |
|                            |
|                            |
|       Box 1                |
|                            |
|                            |
|                            |
|                            |
+--------------+-------------+
               |
               |                     +------------------------------------+
               |                     |                                    |
               |                     |                                    |
               |                     |                                    |
               +-------------------->+         *Box 2*                    |
                                     |                                    |
                                     |                                    |
                                     |                                    |
                                     +------------------------------------+
\~~~
```

Of course the twiddle fences are not escaped with backslashes in my version (that's the only way I can persuade github to render them).

**Comment by visit1985** [comment]
This seams to be a bug indeed. The width of the code block "window" is not calculated correctly is there are preceding spaces.

A simpler repro-case shows that this affects all code blocks not only fenced ones:
```
      this is code
      this is much longer code
```

As a workaround, you can do this (which does not use codeblocks):
```
\+---------+
\|         |
\|  Box 1  |
\|         |
\+---------+
\     |
\     |         +---------+
\     |         |         |
\     +-------->|  *Box 2*  |
\               |         |
\               +---------+
```

**Comment by dsyer** [comment]
Thanks for the workaround. I think it still calculates something wrong because the "Box 2" box is not straight edged at the right:

![image](https://cloud.githubusercontent.com/assets/124075/12445340/a5b4e50e-bf5b-11e5-9119-eeaab4262ad7.png)

I do like the fact that it has a non-inverted background though. Can we have that as a feature too (optional for all code blocks, so asciiart looks better)?

**Comment by dsyer** [comment]
Possibly related (if it's not I'll open a new issue): empty lines in a code block switch off the inverted background, so you get "stripy" code snippets. Looks kind of ugly too. Example:

![image](https://cloud.githubusercontent.com/assets/124075/12446747/d183f618-bf63-11e5-80af-1cc40aa148d5.png)
