### ISSUE TITLE
Add control to open URL in browser

### ISSUE THREAD

**Issue by dsyer** [visit1985/mdp#97]
It would be really neat if the user could open URLs (and images) in a browser, e.g. tab to the link and hit RETURN.

**Comment by visit1985** [comment]
This is a terminal-emulator feature. Some terminals support it natively, some have plugins for it.

**Comment by dsyer** [comment]
I'm just a dumb user here. Any chance of a link to something I can use? I can see that mdp is decorating the links. How can I make the decoration into an active link?

**Comment by visit1985** [comment]
Acording to [this](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/507109) it it seams to be Ctrl + Leftclick in Gnome Terminal and Terminator

Urxvt has a [plugin](https://wiki.archlinux.org/index.php/rxvt-unicode#Clickable_URLs) for it.

If you use another terminal, please google on your own.

**Comment by dsyer** [comment]
I see, so the link URL (which is rendered in a footer by mdp) is clickable. That wasn't what I meant actually: I was thinking the text of the link (not the URL) should be openable, and I was hoping for something on the keyboard. But I suppose what is available a nice feature and might be good enough for some use cases. Not much help with images that are local files though (the link that is rendered by mdp is not a URL so the terminal doesn't recognize it). Is there anything you can do to make images clickable?

**Comment by visit1985** [comment]
There may be ways to do this, but only with a very bad cost-benefit ratio. mdp's purpose is to do presentations in a terminal, and get all the graphical applications out of the way. If you want to klick on links, you can always convert your markdown to html or pdf.

**Comment by DiglidiDudeNG** [comment]
Sorry for necroing this issue, but I think this could have a use for opening links to other markdown documents locally. I can't be the only one who got frustrated from the lack of such a feature from mdp.
