### ISSUE TITLE
Titles with less than 5 characters result in incorrectly aligned text on first subsequent line

### ISSUE THREAD

**Issue by rtyler** [visit1985/mdp#98]
Kind of a weird bug, but it does appear to be tied to the number of characters in the title:

Using the following slide:

```
# Title

* this
* is
* a list
```

With five characters in the `#` title, things look correct: 
![five-char-title](https://cloud.githubusercontent.com/assets/26594/12468044/277e7fda-bf95-11e5-8574-abf773c178f8.png)

If I use a four character (or fewer) title, then the first subsequent line doesn't align properly: 
![four-char-title](https://cloud.githubusercontent.com/assets/26594/12468051/33fe55b4-bf95-11e5-8e22-afcc39587b25.png)

**Comment by visit1985** [comment]
Can't reproduce. Which OS?
